- hosts: 127.0.0.1
  connection: local
  user: vagrant
  sudo: yes

  vars:
    src_dir: /usr/local/src
    bin_dir: /usr/local/bin
    porg_ver: "porg-0.8"
    porg_url: "https://sourceforge.net/projects/porg/files/{{porg_ver}}.tar.gz"
    emacs_ver: "emacs-24.5"
    emacs_url: "http://ftp.gnu.org/gnu/emacs/{{emacs_ver}}.tar.gz"

  tasks:
  - name: apt-get update
    apt: update_cache=yes

  - name: add apt-repo
    apt_repository: repo='ppa:git-core/ppa'

  - name: apt-get packages
    apt: name={{item}} state=latest
    with_items:
      - build-essential
      - make
      - cmake
      - autoconf
      - automake
      - vim
      - git
      - zsh
      - gdb
      - valgrind
      - lcov
      - python-pip
      - jq
      - curl
      - openssl
      - tree
      - tmux
      - imagemagick
      - texinfo
      - libgtk-3-dev
      - libcurl4-openssl-dev
      - libjpeg-dev
      - libpng-dev
      - libgif-dev
      - libncurses5-dev
      - libtiff5-dev
      - libxml2-dev
      - libev-dev
      - libuv-dev
      - libxpm-dev

  - name: download porg
    get_url: url={{porg_url}} dest={{src_dir}}

  - name: extract porg
    unarchive: 
      copy=no 
      src={{src_dir}}/{{porg_ver}}.tar.gz
      dest={{src_dir}}
      creates={{src_dir}}/{{porg_ver}}

  - name: install porg
    shell: >-
      ./configure --prefix=/usr/local --disable-grop &&
      make &&
      make install &&
      make logme
      chdir={{src_dir}}/{{porg_ver}}
      creates={{bin_dir}}/porg

  - name: download emacs
    get_url: url={{emacs_url}} dest={{src_dir}}

  - name: extract emacs
    unarchive: 
      copy=no 
      src={{src_dir}}/{{emacs_ver}}.tar.gz
      dest={{src_dir}}
      creates={{src_dir}}/{{emacs_ver}}

  - name: install emacs
    shell: >-
      ./configure --prefix=/usr/local --with-x &&
      make &&
      porg -lp emacs "make install"
      chdir={{src_dir}}/{{emacs_ver}}
      creates={{bin_dir}}/emacs

  - name: install mydotfiles
    git: 
      repo=https://github.com/kazuhironx/mydotfiles.git
      dest=/home/vagrant/mydotfiles
    sudo: no

  - name: create symlink of .zshrc
    file: src=/home/vagrant/mydotfiles/zsh/.zshrc dest=/home/vagrant/.zshrc owner=vagrant group=vagrant state=link

  - name: create symlink of .tmux.conf
    file: src=/home/vagrant/mydotfiles/tmux/.tmux.conf dest=/home/vagrant/.tmux.conf owner=vagrant group=vagrant state=link

  - name: create symlink of .emacs.d
    file: src=/home/vagrant/mydotfiles/emacs/.emacs.d dest=/home/vagrant/.emacs.d owner=vagrant group=vagrant state=link

  - name: change login shell to zsh
    user: name=vagrant shell=/usr/bin/zsh

  - name: set timezone
    copy: content='Asia/Tokyo\n' dest=/etc/timezone backup=yes
    notify: pdate tzdata

  handlers:
  - name: update tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
